<!--
Comments:
To create index.html, do this in R:

   library(buildDocs)
   setwd(".../docs-csp2015")
   buildDocs("analysis", outLoc=".", copyrightText="")

   # Comment out copyright text, and 'Previous' and 'Next' links since they
   # aren't relevant (and the break).  Ignore the warning.
   library(Smisc)
   streamEdit(list(c = list(at = "<p>&copy; , ", type = "html", fixed = TRUE), 
                   c = list(at = "id=\"previous\">&larr;", type = "html", fixed = TRUE), 
                   c = list(at = "id=\"next\">Next &rarr;", type = "html", fixed = TRUE)), 
              inFile = "index.html", outFile = "index.html")
   
-->

# Tessera Demo at the Conference on Statistical Practice 2015 #

## CSP 2015 Demo ##

### Download Demo Materials ###

The Tessera team will be presenting an interactive demo at the 
<a href="http://www.amstat.org/meetings/csp/2015/" target="_blank">
2015 Conference on Statistical Practice</a> in 
New Orleans on February 21, 2015.

Participants who would like to download the Tessera tools prior to the demo 
please follow these instructions. These tools will allow you to use and test 
Tessera on your own computer without Hadoop or a similar parallel 
processing backend.

1. If you do not already have R version 3.0.2 or later, please download and
install it here: <a href="http://cran.r-project.org" target="_blank">
http://cran.r-project.org</a>. 

2. Optional: You may find the RStudio development environment an easier way
to program in R, but it is not necessary. You may download it here:
<a href="http://www.rstudio.com/" target="_blank">http://www.rstudio.com/</a>.

3. Make sure you have Java JDK (1.4 or newer) installed. If not go here to 
install it: 
<a href="http://www.oracle.com/technetwork/java/javase/downloads/index.html" target="_blank">
http://www.oracle.com/technetwork/java/javase/downloads/index.html</a>.

4. You will need a non-Internet Explorer browser installed on your computer.  Firefox, Safari, or Chrome will all work fine.

5. Open R and execute the following commands to install the Tessera libraries:
   ```{r eval=FALSE, echo=TRUE}
      install.packages(c("devtools", "rJava", "plyr"))
      library(devtools)
      install_github("tesseradata/datadr")
      install_github("tesseradata/trelliscope")
   ```

6. Download the CSP Tessera demo files and unzip them on your computer:
[Tessera_demo_CSP2015.zip](Tessera_demo_CSP2015.zip)

7. The zip file contains a folder called __demos__.  Set your working directory in R to this folder,
using something like `setwd("mypaths/demos")`.  The __demos__ folder 
contains a folder for each of the three demos:  __power_demo__, __netflow_demo__, and __housing_demo__.
Each demonstration folder has a single __.R__ file which contains the code for the demonstration.  
Open that file in R and begin!

#### We look forward to seeing you at CSP! 
